[workspace]
members = [
    "lib",
    "metricsql",
    "runtime"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace.dependencies]
chrono = "0.4.22"
chrono-tz = "0.8.0"
once_cell = "1.14.0"
text-size = "1.1.0"
enquote = "1.1.0"
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.5.3"
regex = "1.6.0"
serde = { version = "1.0.147", features = ["derive"] }
tinyvec = { version = "1.6.0", features = ["alloc"] }
phf = { version = "0.11.0", features = ["macros"] }
thiserror = "1.0.35"
xxhash-rust = { version = "0.8.5", features = ["xxh3", "xxh64"] }