[workspace]
members = [
    "lib",
    "metricsql",
    "runtime"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace.dependencies]
chrono = "0.4.22"
once_cell = "1.14.0"
phf = { version = "0.11.0", features = ["macros"] }
thiserror = "1.0.35"
xxhash-rust = { version = "0.8.5", features = ["xxh3", "xxh64"] }