[workspace]
members = [
    "lib",
    "metricsql",
    "runtime",
    "storage"
]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace.dependencies]
chrono = { version = "0.4.26", features = ["serde"] }
chrono-tz = "0.8.2"
enquote = "1.1.0"
itertools = "0.11.0"
num-traits = "0.2.15"
q_compress = "0.11.6"
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.7.0"
regex = "1.8.4"
regex-syntax = "0.7.2"
rs_unit = "0.0.2"
scopeguard = "1.1.0"
serde = { version = "1.0.164", features = ["derive"] }
serde_with = "3.0.0"
serde_json = "1.0.104"
tinyvec = { version = "1.6.0", features = ["alloc"] }
tracing = "0.1.37"
phf = { version = "0.11.1", features = ["macros"] }
thiserror = "1.0.40"
xxhash-rust = { version = "0.8.6", features = ["xxh3", "xxh64"] }