[package]
name = "metricsql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
enquote = { workspace = true }
logos = "0.12.1"
once_cell = { workspace = true }
regex = {  workspace = true }
text-size = { workspace = true }
thiserror = { workspace = true }
phf = { workspace = true }
lib={ path = "../lib" }

[dev-dependencies]
test-case = "2.2.2"

[lib]
name="metricsql"
path="src/lib.rs"