[package]
name = "metricsql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
enquote = "1.1"
logos = "0.12.1"
once_cell = "1.12.0"
regex= "1.5.6"
rowan="0.15.5"
num-derive = "0.3.3"
num-traits = "0.2.15"
text-size = "1.1.0"
phf = { version = "0.10", features = ["macros"] }

[lib]
name="metricsql"
path="src/lib.rs"