[package]
name = "metricsql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
enquote = "1.1"
logos = "0.12.1"
regex= "1.5.6"
phf = { version = "0.10", features = ["macros"] }

[lib]
name="metricsql"
path="src/lib.rs"