[package]
name = "metricsql_runtime"
description = "A promql execution engine"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
include = [
    "**/*.rs",
    "Cargo.toml",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
glob = "0.3.2"
rs_unit = { workspace = true }
tokio={version = "1", features = ["macros", "test-util", "rt-multi-thread"]}

[dependencies]
agnostic-lite.workspace = true
ahash.workspace = true
async-trait.workspace = true
enquote.workspace = true
blart = "0.4"
clone_dyn = "0.34"
chili.workspace = true
croaring = { version = "2.3" , features = ["alloc"] }
chrono.workspace = true
chrono-tz.workspace = true
effective-limits = "0.5"
get-size.workspace = true
hashify.workspace = true
integer-encoding.workspace = true
itertools.workspace = true
lockfree-object-pool = "0.1"
lru_time_cache = "0.11"
num-traits.workspace = true
prometheus-parse = "0.2"
pco.workspace = true
rand.workspace = true
rand_distr.workspace = true
rayon.workspace = true
regex.workspace = true
serde.workspace = true
small-map.workspace = true
smallvec.workspace = true
thiserror.workspace = true
scopeguard.workspace = true
tracing.workspace = true
xxhash-rust.workspace = true
metricsql_common={ path = "../common" }
metricsql_parser={ path = "../parser" }
futures.workspace = true
iter-set-ops = "0.2"

[features]
tokio = ["agnostic-lite/tokio", "metricsql_common/tokio"]
smol = ["agnostic-lite/smol", "metricsql_common/smol"]
