[package]
name = "runtime"
version = "0.1.0"
edition = "2021"
include = [
    "**/*.rs",
    "Cargo.toml",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.11.0", features = ["macros"] }
enquote = "1.1"
regex = "1.5.6"
byte-slice-cast = "1.2.1"
byte-pool = "0.2.3"
clone_dyn = "0.1.0"
chrono = "0.4.19"
chrono-tz = "0.6.3"
once_cell = "1.12.0"
integer-encoding = "3.0.4"
lockfree-object-pool = "0.1.3"
metrics = "0.20.1"
effective-limits = "0.5.4"
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.5.3"
tinyvec = { version = "1.6.0", features = ["alloc"] }
thiserror = "1.0.31"
scopeguard = "1.1.0"
dashmap = "5.3.4"
pydeco = "0.1.0"
xxhash-rust = "0.8.5"
lib={ path = "../lib" }
metricsql={ path = "../metricsql" }

[profile.release]
lto = true
