[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
async-recursion = "1.0.0"
datafusion = { version = "26" }
lib = { path = "../lib" }
metricsql = { path = "../metricsql" }
snafu = "0.7.4"
tokio = "1.29.1"
tracing = { workspace = true }

[lib]
name = "storage"