[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
async-recursion = "1.0.0"
datafusion = { version = "26" }
futures = "0.3.17"
lib = { path = "../lib" }
metricsql = { path = "../metricsql" }
rayon = { workspace = true }
runtime = { path = "../runtime" }
regex = { workspace = true }
regex-syntax = { workspace = true }
snafu = "0.7.4"
tokio = "1.29.1"
tracing = { workspace = true }

[lib]
name = "storage"