[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.44"
async-recursion = "1.0.0"
async-trait = "0.1.51"
chrono = { workspace = true }
connectorx = "0.2.4-alpha.7"
datafusion = { version = "11" }
derive_builder = "0.11"
futures = "0.3.17"
itertools = { workspace = true }
lib = { path = "../lib" }
metricsql = { path = "../metricsql" }
once_cell = "1.8.0"
paste = "1.0.6"
rayon = { workspace = true }
rstest = "0.5.2"
runtime = { path = "../runtime" }
regex = { workspace = true }
regex-syntax = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
snafu = "0.7.4"
tokio = "1.29.1"
tracing = { workspace = true }
xxhash-rust = { workspace = true }

[lib]
name = "storage"
