[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.44"
arrow = { version = "46", features = ["prettyprint", "ffi"] }
arrow2 = { version = "0.17", default-features = false }
async-recursion = "1.0.0"
async-trait = "0.1.51"
chrono = { workspace = true }
# Remote query execution for a variety of DBs
connectorx = { git = "https://github.com/splitgraph/connector-x", branch = "datafusion-32-upgrade", features = ["dst_arrow", "src_postgres", "src_mysql", "src_sqlite"] }
datafusion = "32.0.0"
datafusion-common = "32.0.0"
datafusion-expr = "32.0.0"
derive_builder = "0.11"
humantime = "2.1"
humantime-serde = "1.1"
futures = "0.3"
itertools = { workspace = true }
lib = { path = "../lib" }
metricsql = { path = "../metricsql" }
once_cell = "1.8.0"
paste = "1.0.6"
rayon = { workspace = true }
rstest = "0.5.2"
runtime = { path = "../runtime" }
regex = { workspace = true }
regex-syntax = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
snafu = "0.7.4"
tokio = "1"
tracing = { workspace = true }
xxhash-rust = { workspace = true }
ahash = "0.7.7"
arc-swap = "1.6.0"
toml = { version = "0.8.8", features = [] }

[lib]
name = "storage"
