[package]
name = "metricsql_common"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name="metricsql_common"
path="src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agnostic-lite.workspace = true
ahash.workspace = true
cfg-if.workspace = true
chili.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
byte-pool = "0.2"
futures.workspace = true
gxhash = { version = "3.5", optional = true }
get-size.workspace = true
integer-encoding.workspace = true
lockfree-object-pool = "0.1"
lru_time_cache = "0.11"
rand.workspace = true
regex.workspace = true
regex-syntax.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_regex.workspace = true
small-map.workspace = true
strum.workspace = true
thiserror.workspace = true
futures-util.workspace = true

[dev-dependencies]
test-case = "3.3"
serde_json = "1.0"
tokio = "1.46"

[features]
default = ["tokio"]
tokio = ["agnostic-lite/tokio"]
async-std = ["agnostic-lite/async-std"]
smol = ["agnostic-lite/smol"]
gxhash = ["dep:gxhash"]
legacy_newline = []
