[package]
name = "metrics"
version = "0.1.0"
edition = "2021"

[lib]
name="metrics"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand= "1.7.0"
